name: Examples

on:
  schedule:
    # Run examples weekly to ensure they stay functional
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  run-examples:
    name: Run Examples
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: '0.15.1'

      - name: Build add_two_numbers example
        run: zig build add_two_numbers
        timeout-minutes: 2

      - name: Verify example output
        run: |
          output=$(zig build add_two_numbers 2>&1)
          echo "$output"
          
          # Check for success message
          if echo "$output" | grep -q "Success! Homomorphic addition computed correctly"; then
            echo "✓ Example ran successfully"
          else
            echo "✗ Example did not complete successfully"
            exit 1
          fi

